[tool.poetry]
name = "joelutilities"
version = "0.1.0"
description = ""
authors = ["not-relevant-is-it <joel.edwardson1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.4"
pydantic = "^1.8.2"
jsonpickle = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
